enum FeatureFlag {
  FEATURE_FLAG_CONNECTOR_OVERVIEW = "FEATURE_FLAG_CONNECTOR_OVERVIEW",
  FEATURE_FLAG_EDIT_CONNECTOR = "FEATURE_FLAG_EDIT_CONNECTOR",
  FEATURE_FLAG_CONFIGURATION_LINKS = "FEATURE_FLAG_CONFIGURATION_LINKS",
}

export { FeatureFlag };
