enum FeatureFlag {
  FEATURE_FLAG_TOPNAV_DROPDOWN = "FEATURE_FLAG_TOPNAV_DROPDOWN",
  FEATURE_FLAG_TOPIC_OVERVIEW = "FEATURE_FLAG_TOPIC_OVERVIEW",
  FEATURE_FLAG_CONNECTOR_OVERVIEW = "FEATURE_FLAG_CONNECTOR_OVERVIEW",
}

export { FeatureFlag };
