import {
  requestTopicClaim,
  requestTopicDeletion,
  requestTopicEdit,
  getTopicDetailsPerEnv,
  getTopicNames,
  getTopicRequests,
  getTopicTeam,
  getTopics,
  requestTopicPromotion,
  updateTopicDocumentation,
} from "src/domain/topic/topic-api";
import {
  DeleteTopicPayload,
  Topic,
  TopicDetailsPerEnv,
  TopicDocumentationMarkdown,
  TopicNames,
  TopicOverview,
  TopicRequest,
  TopicRequestOperationTypes,
  TopicRequestStatus,
  TopicSchemaOverview,
  TopicTeam,
  TopicType,
  TOPIC_MESSAGE_DEFAULT_USER_GROUP_ID,
} from "src/domain/topic/topic-types";

export {
  requestTopicClaim,
  requestTopicDeletion,
  requestTopicEdit,
  getTopicDetailsPerEnv,
  getTopicNames,
  getTopicRequests,
  getTopicTeam,
  getTopics,
  requestTopicPromotion,
  updateTopicDocumentation,
  TOPIC_MESSAGE_DEFAULT_USER_GROUP_ID,
};
export type {
  DeleteTopicPayload,
  Topic,
  TopicDetailsPerEnv,
  TopicDocumentationMarkdown,
  TopicNames,
  TopicOverview,
  TopicRequest,
  TopicRequestOperationTypes,
  TopicRequestStatus,
  TopicSchemaOverview,
  TopicTeam,
  TopicType,
};
