blank_issues_enabled: true
contact_links:
  - name: Aiven Security Bug Bounty
    url: https://hackerone.com/aiven_ltd
    about: Our bug bounty program.
  - name: Klaw Community Support
    url: https://aiven.io/community/forum/c/open-source/12
    about: Please ask and answer questions here in the Aiven Community Forum.
  - name: Klaw Github discussions
    url: https://github.com/aiven/klaw/discussions
    about: Or ask and answer questions here in Github Discussions.