import { transformTopicApiResponse } from "src/domain/topics/topic-transformer";
import { Topic, TopicDTOApiResponse } from "src/domain/topics/topics-types";

describe("topic-transformer.ts", () => {
  describe("transforms API response into components of topics", () => {
    it("transforms a response with two entries", () => {
      const apiResponse: TopicDTOApiResponse = [
        [
          {
            topicid: 1012,
            sequence: "341",
            totalNoPages: "1",
            currentPage: "1",
            allPageNos: ["1"],
            topicName: "demotopic1",
            noOfPartitions: 2,
            description: "Topic description",
            documentation: null,
            noOfReplcias: "2",
            teamname: "DevRel",
            cluster: "1",
            clusterId: null,
            environmentsList: ["DEV"],
            showEditTopic: false,
            showDeleteTopic: false,
            topicDeletable: false,
          },
          {
            topicid: 1008,
            sequence: "342",
            totalNoPages: "1",
            currentPage: "1",
            allPageNos: ["1"],
            topicName: "newaudittopic",
            noOfPartitions: 1,
            description: "Topic description",
            documentation: null,
            noOfReplcias: "2",
            teamname: "Ospo",
            cluster: "1",
            clusterId: null,
            environmentsList: ["DEV", "TST"],
            showEditTopic: false,
            showDeleteTopic: false,
            topicDeletable: false,
          },
        ],
      ];
      const result: Topic[] = [
        {
          topicid: 1012,
          sequence: "341",
          totalNoPages: "1",
          currentPage: "1",
          allPageNos: ["1"],
          topicName: "demotopic1",
          noOfPartitions: 2,
          description: "Topic description",
          documentation: null,
          noOfReplcias: "2",
          teamname: "DevRel",
          cluster: "1",
          clusterId: null,
          environmentsList: ["DEV"],
          showEditTopic: false,
          showDeleteTopic: false,
          topicDeletable: false,
        },
        {
          topicid: 1008,
          sequence: "342",
          totalNoPages: "1",
          currentPage: "1",
          allPageNos: ["1"],
          topicName: "newaudittopic",
          noOfPartitions: 1,
          description: "Topic description",
          documentation: null,
          noOfReplcias: "2",
          teamname: "Ospo",
          cluster: "1",
          clusterId: null,
          environmentsList: ["DEV", "TST"],
          showEditTopic: false,
          showDeleteTopic: false,
          topicDeletable: false,
        },
      ];

      expect(transformTopicApiResponse(apiResponse)).toEqual(result);
    });

    it("transforms a response with four entries", () => {
      const apiResponse: TopicDTOApiResponse = [
        [
          {
            topicid: 1012,
            sequence: "341",
            totalNoPages: "1",
            currentPage: "1",
            allPageNos: ["1"],
            topicName: "demotopic1",
            noOfPartitions: 2,
            description: "Topic description",
            documentation: null,
            noOfReplcias: "2",
            teamname: "DevRel",
            cluster: "1",
            clusterId: null,
            environmentsList: ["DEV"],
            showEditTopic: false,
            showDeleteTopic: false,
            topicDeletable: false,
          },
          {
            topicid: 1008,
            sequence: "342",
            totalNoPages: "1",
            currentPage: "1",
            allPageNos: ["1"],
            topicName: "newaudittopic",
            noOfPartitions: 1,
            description: "Topic description",
            documentation: null,
            noOfReplcias: "2",
            teamname: "Ospo",
            cluster: "1",
            clusterId: null,
            environmentsList: ["DEV", "TST"],
            showEditTopic: false,
            showDeleteTopic: false,
            topicDeletable: false,
          },
          {
            topicid: 1002,
            sequence: "343",
            totalNoPages: "1",
            currentPage: "1",
            allPageNos: ["1"],
            topicName: "testospo2",
            noOfPartitions: 1,
            description: "Topic description",
            documentation: null,
            noOfReplcias: "2",
            teamname: "Ospo",
            cluster: "1",
            clusterId: null,
            environmentsList: ["DEV"],
            showEditTopic: false,
            showDeleteTopic: false,
            topicDeletable: false,
          },
        ],
        [
          {
            topicid: 1003,
            sequence: "344",
            totalNoPages: "1",
            currentPage: "1",
            allPageNos: ["1"],
            topicName: "testtopic",
            noOfPartitions: 1,
            description: "Topic description",
            documentation: null,
            noOfReplcias: "2",
            teamname: "DevRel",
            cluster: "1",
            clusterId: null,
            environmentsList: ["DEV"],
            showEditTopic: false,
            showDeleteTopic: false,
            topicDeletable: false,
          },
        ],
      ];
      const result: Topic[] = [
        {
          topicid: 1012,
          sequence: "341",
          totalNoPages: "1",
          currentPage: "1",
          allPageNos: ["1"],
          topicName: "demotopic1",
          noOfPartitions: 2,
          description: "Topic description",
          documentation: null,
          noOfReplcias: "2",
          teamname: "DevRel",
          cluster: "1",
          clusterId: null,
          environmentsList: ["DEV"],
          showEditTopic: false,
          showDeleteTopic: false,
          topicDeletable: false,
        },
        {
          topicid: 1008,
          sequence: "342",
          totalNoPages: "1",
          currentPage: "1",
          allPageNos: ["1"],
          topicName: "newaudittopic",
          noOfPartitions: 1,
          description: "Topic description",
          documentation: null,
          noOfReplcias: "2",
          teamname: "Ospo",
          cluster: "1",
          clusterId: null,
          environmentsList: ["DEV", "TST"],
          showEditTopic: false,
          showDeleteTopic: false,
          topicDeletable: false,
        },
        {
          topicid: 1002,
          sequence: "343",
          totalNoPages: "1",
          currentPage: "1",
          allPageNos: ["1"],
          topicName: "testospo2",
          noOfPartitions: 1,
          description: "Topic description",
          documentation: null,
          noOfReplcias: "2",
          teamname: "Ospo",
          cluster: "1",
          clusterId: null,
          environmentsList: ["DEV"],
          showEditTopic: false,
          showDeleteTopic: false,
          topicDeletable: false,
        },

        {
          topicid: 1003,
          sequence: "344",
          totalNoPages: "1",
          currentPage: "1",
          allPageNos: ["1"],
          topicName: "testtopic",
          noOfPartitions: 1,
          description: "Topic description",
          documentation: null,
          noOfReplcias: "2",
          teamname: "DevRel",
          cluster: "1",
          clusterId: null,
          environmentsList: ["DEV"],
          showEditTopic: false,
          showDeleteTopic: false,
          topicDeletable: false,
        },
      ];

      expect(transformTopicApiResponse(apiResponse)).toEqual(result);
    });

    it("transforms a response with no entries", () => {
      const apiResponse: TopicDTOApiResponse = [];
      const result: Topic[] = [];

      expect(transformTopicApiResponse(apiResponse)).toEqual(result);
    });
  });
});
