/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
  /** User can authenticate themselves with their username as password */
  "/user/authenticate": {
    /** Exchange username and password to an authentication token.  The token can be later used as authentication mechanism for other API endpoints. */
    post: operations["userAuthentication"];
  };
};

export type components = {
  schemas: {
    CommonError: {
      /**
       * message
       * @description Description for user why a certain operation failed
       */
      message?: string;
    };
    UserAuthenticationRequest: {
      /**
       * username
       * Format: email
       * @description Username
       * @example john.doe@klaw-project.io
       */
      username: string;
      /** password */
      password: string;
    };
    UserAuthenticationResponse: {
      /**
       * token
       * @description Klaw authentication token
       * @example PgaBBvZpb30NUAZDwiJeAoTppfPa6NyX
       */
      token: string;
      /**
       * Token type
       * @example bearer
       * @enum {string}
       */
      token_type: "bearer";
    };
  };
};

export type operations = {
  /** Exchange username and password to an authentication token.  The token can be later used as authentication mechanism for other API endpoints. */
  userAuthentication: {
    responses: {
      /** Successful authentication */
      200: {
        content: {
          "application/json": components["schemas"]["UserAuthenticationResponse"];
        };
      };
      /** Invalid credentials */
      403: {
        content: {
          "application/json": components["schemas"]["CommonError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserAuthenticationRequest"];
      };
    };
  };
};

export type external = {};

export enum ApiPaths {
  userAuthentication = "/user/authenticate",
}
