drop table if exists kwtopicrequests;
drop table if exists kwtopics;
drop table if exists kwaclrequests;
drop table if exists kwacls;
drop table if exists kwschemarequests;
drop table if exists kwavroschemas;
drop table if exists kwkafkaconnectorrequests;
drop table if exists kwkafkaconnector;
drop table if exists kwteams;
drop table if exists kwusers;
drop table if exists kwregisterusers;
drop table if exists kwenv;
drop table if exists kwactivitylog;
drop table if exists kwproperties;
drop table if exists kwclusters;
drop table if exists kwrolespermissions;
drop table if exists kwtenants;
drop table if exists kwproductdetails;
drop table if exists kwkafkametrics;
drop table if exists kwmetadataupdates;

commit;