name: Coral setup and install dependencies
description:
  This action installs node and pnpm in the correct version. 
  It installs all needed dependencies and handles the pnpm store for caching. 
  Node version and pnpm version should not be changed.

runs:
  using: "composite"

  steps:
    - name: Set Node and pnpm versions
      id: versions
      working-directory: ./coral
      shell: bash
      run: |
        NODE_VERSION=$(jq -r '.engines.node' package.json)
        PNPM_VERSION=$(jq -r '.engines.pnpm' package.json)
        echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_OUTPUT
        echo "PNPM_VERSION=$PNPM_VERSION" >> $GITHUB_OUTPUT

    - name: Setup node.js
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: ${{ steps.versions.outputs.NODE_VERSION }}

    - name: Setup pnpm
      uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
      with:
        version: ${{ steps.versions.outputs.PNPM_VERSION }}
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Setup pnpm cache
      uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      working-directory: ./coral
      run: pnpm install