name: Coral PR Pipeline

on:
  workflow_call

permissions:
  contents: read

jobs:
  static_code_analysis:
    name: Static code analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          persist-credentials: false

      - name: Setup coral
        uses: ./.github/actions/setup-coral

      - name: Run static checks
        working-directory: ./coral
        run: pnpm run lint

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          persist-credentials: false

      - name: Setup coral
        uses: ./.github/actions/setup-coral

      - name: Run unittests
        working-directory: ./coral
        run: pnpm run test-ci