name: Coral PR Pipeline

on:
  pull_request:
    paths:
      - 'coral/**'
      - '!coral/types/api.d.ts'

permissions:
  contents: read

jobs:
  static_code_analysis:
    name: Static code analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          persist-credentials: false

      - name: Setup coral
        uses: ./.github/actions/setup-coral

      - name: Run static checks
        working-directory: ./coral
        run: pnpm run lint

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          persist-credentials: false

      - name: Setup coral
        uses: ./.github/actions/setup-coral

      - name: Run unittests
        working-directory: ./coral
        run: pnpm run test-ci