name: Coral PR Pipeline

on:
  pull_request:
    paths:
      - "coral/**"
      - "!coral/types/api.d.ts"

permissions:
  contents: read

jobs:
  static_code_analysis:
    name: Static code analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          persist-credentials: false

      - name: Setup coral
        uses: ./.github/actions/setup-coral

      - name: Run static checks
        working-directory: ./coral
        run: pnpm run lint

  test1:
    name: test1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          persist-credentials: false
      - name: Setup coral
        uses: ./.github/actions/setup-coral
      - run: pnpm run test-ci --shard=1/3

  test2:
    name: test2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          persist-credentials: false
      - name: Setup coral
        uses: ./.github/actions/setup-coral
      - run: pnpm run test-ci --shard=2/3

  test3:
    name: test3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          persist-credentials: false
      - name: Setup coral
        uses: ./.github/actions/setup-coral
      - run: pnpm run test-ci --shard=3/3
