# This workflow is not automatically triggered, but needs to be
# called from e.g. another workflow file. It enables us to
# reuse the jobs run here in different workflows.
# Please note that in order to run this jobs, the
# code needs to be checked already out when using the job
name: Coral related jobs

on:
  workflow_call

permissions:
  contents: read

# The jobs for coral can be triggered by different
# workflows / scenarios. We want to make sure that
# an already running job is cancelled as soon as a new
# event required this jobs to be run again.
concurrency:
  group: coral-jobs-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  type-check:
    name: TypeScript compiler
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          persist-credentials: false

      - name: Setup coral
        uses: ./.github/actions/setup-coral

      - name: Run tsc
        working-directory: ./coral
        run: pnpm run tsc

  static_code_analysis:
    name: Static code analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.2
        with:
          persist-credentials: false

      - name: Setup coral
        uses: ./.github/actions/setup-coral

      - name: Run static checks
        working-directory: ./coral
        run: pnpm run lint

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.2
        with:
          persist-credentials: false

      - name: Setup coral
        uses: ./.github/actions/setup-coral

      - name: Run unittests
        working-directory: ./coral
        run: pnpm run test-ci