# This workflow is called on every merges to the main branch
# Changes will not be applied to the main branch until the pull request
# passes the pipeline checks and is merged  successfully.
name: PR/Push to main pipeline

on:
  workflow_call

jobs:
  merge-to-main:
    name: Merge to main pipeline
    runs-on: ubuntu-latest
    steps:
      - name: maven-workflow
        uses: ./.github/workflows/maven-jobs.yaml
      - name: coral-workflow
        uses: ./.github/workflows/coral-jobs.yaml
