# This workflow is called on every merges to the main branch
# Changes will not be applied to the main branch until the pull request
# passes the pipeline checks and is merged  successfully.
# change for new commit
name: PR/Push to main pipeline

on:
  pull_request_review:
    types: [submitted]
    branches:
      - fake-main
  workflow_dispatch:

jobs:
  coral-workflow-for-merge-to-main:
    if: github.event.review.state == 'approved'
    name: Run coral workflow before enabling merge to main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: coral-workflow
        uses: ./.github/workflows/coral-jobs.yaml

  maven-workflow-for-merge-to-main:
    if: github.event.review.state == 'approved'
    name: Run maven workflow before enabling merge to main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: maven-workflow
        uses: ./.github/workflows/maven-jobs.yaml

  merge-to-main:
    if: github.event.review.state == 'approved'
    name: Status check for enabling merging to main
    runs-on: ubuntu-latest
    needs: [ maven-workflow-for-merge-to-main, coral-workflow-for-merge-to-main ]

    steps:
      - name: Confirm check
        run: echo "🎉 this was successful"

