# This workflow is called on every merges to the main branch
# Changes will not be applied to the main branch until the pull request
# passes the pipeline checks and is merged  successfully.
name: PR/Push to main pipeline

on:
  push:
    branches: ["fake-main"]

jobs:
#  maven-workflow:
#    uses: ./.github/workflows/maven-jobs.yaml
  coral-workflow:
    uses: ./.github/workflows/coral-jobs.yaml
