# This workflow is called for every pull request regardless which branch its targets
#
# 'coral-workflow' runs the jobs for coral when
# - a PR is opened, synchronize, or reopened
# - & there are changes inside `coral` directory
# -> it does _not_ differentiate between a PR that is ready for review or a draft
#
# 'coral-workflow' runs the jobs for coral when
# - a PR is opened, synchronize, or reopened
# - & there are changes detected in the directories cluster-api and core
#     the file pom.xml
# - & the PR is not in DRAFT status
# - OR the PR is in draft status, but was marked as "Ready for review"
name: Pull Request pipeline

on:
  pull_request:
  workflow_dispatch:

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      changes-maven: ${{ steps.check-changed-dirs.outputs.changes-maven }}
      changes-coral: ${{ steps.check-changed-dirs.outputs.changes-coral }}
    steps:
      - name: Checkout code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - id: check-changed-dirs
        name: Check directories of changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^coral/'; then
            echo "Changes detected in coral directory 🪸"
            echo "changes-coral=true" >> $GITHUB_OUTPUT
          fi
          if git diff --name-only HEAD^ HEAD | grep -qE '^cluster-api/|^core/|^pom.xml$'; then
            echo "Changes detected for cluster-api/core or pom.xml"
            echo "changes-maven=true" >> $GITHUB_OUTPUT
          fi


  maven-workflow:
    needs: check-changes
    if: (github.event.pull_request.draft == false || github.event.action == 'ready_for_review') && needs.check-changes.outputs.changes-maven == 'true'
    uses: ./.github/workflows/jobs-maven.yaml
  coral-workflow:
    needs: check-changes
    if: needs.check-changes.outputs.changes-coral == 'true'
    uses: ./.github/workflows/jobs-coral.yaml